apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-apex
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-apex@sha256:f5f96e8ac9e599f88d167c904b20b283db19eb144ec7c1de6ac2b47132676c92
        name: my-python
        resources: {}
status: {}
